ALTER TABLE tasks
    ADD COLUMN data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN status ENUM('A fazer', 'Em andamento', 'Concluída') DEFAULT 'A fazer';
